server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka,http://127.0.0.1:7001/eureka

spring:
  application:
    name: client-server